### ISSUE TITLE
Compatibility checks between logger/observer and problems

### ISSUE THREAD

**Issue by brockho** [numbbo/numbbo#131]
Do we want (or even can have) a general prescribed way for conducting consistency checks between the logging/observer facilities and the problems that are compatible with these modules? For example, a multiobjective logger which is wrapped around a single-objective problem might not result in correct code and such combinations should be prevented/checked by the code.

**Comment by ttusar** [comment]
I have added such a check to the initialization function of the biobjective and toy loggers.

**Comment by ttusar** [comment]
@oaelhara did this for the bbob logger, so the issue can be closed.
