### ISSUE TITLE
Reorganizing platform- and compiler-dependent definitions

### ISSUE THREAD

**Issue by ttusar** [numbbo/numbbo#144]
The file `coco_utilities.c` is now full of platform- and compiler-dependent definitions (it's getting a bit messy). Some can be found also in `coco.h`. It seems that `coco_platform.h` was created exactly for this purpose, so we should consider moving all definitions to this file (and also reorganize them).

**Comment by nikohansen** [comment]
Looks like a pretty good idea to me :-)

**Comment by ttusar** [comment]
Done.
