### ISSUE TITLE
Use platform-independent makefiles

### ISSUE THREAD

**Issue by ttusar** [numbbo/numbbo#153]
Possibly as described here: http://stackoverflow.com/questions/4058840/makefile-that-distincts-between-windows-and-unix-like-systems

**Comment by brockho** [comment]
I have seen this page already before, however, it does not say how to deal with Windows installations with Cygwin (for which the normal makefile could be used). It also looked as if it makes the makefiles even less readable. Hence, we decided to deal with different systems by letting the do.py command detect the operating system and environment and create the right makefile by renaming either makefile.in or Makefile_win_gcc.in.

**Comment by ttusar** [comment]
Here they describe how Cygwin can be detected in a Makefile: http://stackoverflow.com/questions/714100/os-detecting-makefile
However, I do agree that this would make the Makefiles rather unreadable, so I will just close this issue.
