### ISSUE TITLE
Postprocessing EGO data from Coco data-archive causes error with postprocessing

### ISSUE THREAD

**Issue by brockho** [numbbo/numbbo#156]
Loading and postprocessing the EGO data from coco/BBOB/data-archive/Other/ causes an error with the postprocessing.

Error message:
[...]
..\bbob_pproc\pproc.py:785: UserWarning: Inconsistent data found for function 5
in 20-D (see also above)
  warnings.warn("Inconsistent data found for function " + str(self.funcId) + " i
n %d-D (see also above)" % self.dim)
..\bbob_pproc\pproc.py:1438: UserWarning: same DataSet found twice, second one f
rom ['C:\\Users\\dimo\\Desktop\\coco\\BBOB\\data-archive\\Other\\_extracted_ego_
data\\ego_data_bernd\\bbobexp_f6.info'] is disregarded for instances [1, 2, 3, 4
, 5, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
  + str(i.instancenumbers))
..\bbob_pproc\pproc.py:1438: UserWarning: same DataSet found twice, second one f
rom ['C:\\Users\\dimo\\Desktop\\coco\\BBOB\\data-archive\\Other\\_extracted_ego_
data\\ego_data_bernd\\bbobexp_f7.info'] is disregarded for instances [1, 2, 3, 4
, 5, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
  + str(i.instancenumbers))
..\bbob_pproc\pproc.py:1438: UserWarning: same DataSet found twice, second one f
rom ['C:\\Users\\dimo\\Desktop\\coco\\BBOB\\data-archive\\Other\\_extracted_ego_
data\\ego_data_bernd\\bbobexp_f8.info'] is disregarded for instances [1, 2, 3, 4
, 5, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
  + str(i.instancenumbers))
..\bbob_pproc\pproc.py:1438: UserWarning: same DataSet found twice, second one f
rom ['C:\\Users\\dimo\\Desktop\\coco\\BBOB\\data-archive\\Other\\_extracted_ego_
data\\ego_data_bernd\\bbobexp_f9.info'] is disregarded for instances [1, 2, 3, 4
, 5, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
  + str(i.instancenumbers))
Traceback (most recent call last):
  File "rungeneric.py", line 281, in <module>
    res = main()
  File "rungeneric.py", line 257, in main
    + ["-o", outputdir, alg])
  File "..\bbob_pproc\rungeneric1.py", line 285, in main
    dsList = DataSetList(filelist, genericsettings.verbose)
  File "..\bbob_pproc\pproc.py", line 1377, in __init__
    ds.consistency_check()
  File "..\bbob_pproc\pproc.py", line 855, in consistency_check
    warnings.warn(self.pickleFile + '  double instances in ' + str(self.instance
numbers))
AttributeError: DataSet instance has no attribute 'pickleFile'

**Comment by oaelhara** [comment]
The data that is in the svn has duplicates.
Should work fine with the newly added file instead:
coco/BBOB/data-archive/Other/ego_data_bernd.tar.gz

**Comment by brockho** [comment]
There was an additional 'problem' with the consistency check when the algorithm data was split into separate folders but the merged data was still complete. I now removed this (too early) consistency check in the code such that this issue #156 can be closed
