### ISSUE TITLE
Initialization of observers

### ISSUE THREAD

**Issue by ttusar** [numbbo/numbbo#161]
There might be an conceptual problem with how the observers/loggers are handled currently.

The user is supposed to access the problems of a suite in this way:
````
for (problem_index = 0; problem_index >= 0; problem_index = coco_suite_get_next_problem_index(SUITE_NAME, problem_index, SUITE_OPTIONS)) {
  problem = coco_suite_get_problem(SUITE_NAME, problem_index);
  problem = coco_problem_add_observer(problem, OBSERVER_NAME, OBSERVER_OPTIONS);
  do_some_optimization(problem);
  coco_problem_free(problem);
}
````
The observer/logger is added to every problem independently of anything else (for example, previously observed problems). This kind of interface does not allow to have some continuance when logging, i.e., based on this logic, each log should be independent of others. If we wish to produce logs similar to the ones from the "old" COCO (where one info file contained the summary over all instances and dimensions of the same function) and especially if we wish to keep the number of log files low, then this won't do.

So, either we leave the interface as is and come to terms with 7500+ log files for the MO suite or we do something like this:
````
observer = coco_observer_initialize(OBSERVER_NAME, OBSERVER_OPTIONS);

for (problem_index = 0; problem_index >= 0; problem_index = coco_suite_get_next_problem_index(SUITE_NAME, problem_index, SUITE_OPTIONS)) {
  problem = coco_suite_get_problem(SUITE_NAME, problem_index);
  problem = coco_problem_add_observer(problem, observer);
  do_some_optimization(problem);
  coco_problem_free(problem);
}

coco_observer_free(observer);
````
Needless to say, I'm rooting for \# 2...

Regarding yesterday's discussion on this issue with @brockho: using a static variable to detect whether an observer was added for the first time would "kind of do", but would be a really patchy solution with lots of potential problems when COCO is handled by a creative user.

**Comment by nikohansen** [comment]
Looks like a good solution to me.

**Comment by brockho** [comment]
The single-objective observers should also follow now the same principle of initialization as @ttusar showcased with the multiobjective one.

**Comment by ttusar** [comment]
This is now done for the toy observer as well, so only the bbob2009 observer/logger needs to be updated.

**Comment by nikohansen** [comment]
This is the latest idea
```
  coco_suite_t *suite;
  coco_observer_t *observer;
  coco_problem_t *problem;

  observer = coco_observer(observer_name, observer_options);
  suite = coco_suite(suite_name, suite_instance, suite_options, observer);

  while ((problem = coco_suite_get_next_problem(suite)) != NULL) {
    optimizer(problem);
  }
  coco_suite_free(suite);
  coco_observer_free(observer);  // could be done by the suite
```

**Comment by ttusar** [comment]
This has now been handled, but the question of being able to have two observers still remains. I'm closing this issue and opening a new one.
