### ISSUE TITLE
Accessing function_id and instance_id from the logger

### ISSUE THREAD

**Issue by ttusar** [numbbo/numbbo#163]
Both current non-toy loggers (`logger_bbob2009` and `logger_mo`) need to access `coco_problem`'s `function_id` and `instance_id`. The two are native to the suite and are thus currently not visible/available from within `coco_problem`. 

The current "solution" used by `logger_bbob2009` is to retrieve the `function_id`/`instance_id` by invoking some `suite_bbob2009` function, which is not appropriate if we wish to keep the logger separated from the suite. 

I see two ways of handling this. 

1. The `function_id` and `instance_id` fields are added to `coco_problem` in the same way as it is already done with `index`, which also depends on the suite. 

2. The suite wraps the problem and uses the `data` filed to store the information on `function_id`, `instance_id` and `index` (`index` is thus removed from the problem). It is then the job of the suite constructor/destructor to handle this data field. 

Any thoughts? 

EDIT: `problem_name` and `problem_id` are also suite-dependent...

**Comment by nikohansen** [comment]
I could see two other solutions:

3. let the invoked `suite_bbob2009` function(s) depend on the logged suite (e.g. as a function pointer passed to the logger). 

4. use invariably `problem_id` to identify the problem and, in case, retrieve `function_id` and `instance_id` from it. An example ID is `bbob2009_f06_i01_d10` which should be self-explanatory for how the syntax works. The number of digits after the character should be variable in general.

**Comment by ttusar** [comment]
I'm aware of your second proposed solution (I believe it's even suggested somewhere in the comments of the code), but I would prefer storing two int values to parsing strings... 

I think the first proposal is much better.

**Comment by nikohansen** [comment]
I don't see the big disadvantage with parsing a string, as it is anyway hidden in a function like `coco_get_function_instance`. More annoying is the memory management, but as we already have the id-string there is no added disadvantage. I do see an advantage to do things explicit (via a data type) rather than implicit (via a naming convention). On the other hand, by expanding the data type explicitly we duplicate information that we already have in the id-string. Duplication seems rarely a good idea to me.

**Comment by ttusar** [comment]
Solved by adding the following fields to `coco_problem_t`:
````
problem->suite_dep_index
problem->suite_dep_function_id
problem->suite_dep_instance_id
````
