### ISSUE TITLE
Implement verbosity in observers/loggers

### ISSUE THREAD

**Issue by ttusar** [numbbo/numbbo#187]
Observers/loggers should output information w.r.t. the given verbosity value.

What is the convention for this (what does each verbosity value mean)?

**Comment by nikohansen** [comment]
AFAIK there hasn't been a convention established yet.

**Comment by ttusar** [comment]
COCO now supports four logging levels:
- `COCO_ERROR`: only error messages are output
- `COCO_WARNING`: error and warning messages are output
- `COCO_INFO`: error, warning and info messages are output
- `COCO_DEBUG`: error, warning, info and debug messages are output

The default is `COCO_WARNING`. A user can overwrite this value through the observer option `log_level` (it can take values: `error`, `warning`, `info`, `debug`). 

In addition to the previously existing functions `coco_error()` and `coco_warning()`, we now have also `coco_info()` and `coco_debug()`. All these functions check the logging level before printing the message. However, when a lot of data needs to be prepared before `coco_debug()` is called (for example), this code should be preceded by `if (coco_log_level >= COCO_DEBUG)`.

Some output in `logger_bbob2009.c` that was previously only done if "verbosity was > 2", is now handled using `coco_info()`.
