### ISSUE TITLE
Solve implicit declaration of function 'snprintf'

### ISSUE THREAD

**Issue by ttusar** [numbbo/numbbo#191]
`snprintf` is used 47 times throughout the code. We now have the `coco_strdupf` function that should be used instead.

**Comment by nikohansen** [comment]
this might be an opportunity to also simplify the construction of the bbob functions / testbed with helper funcitons, as `snprintf` is used for constructing the `problem_id`

**Comment by ttusar** [comment]
Since the latest rewriting of the code, most of calls to `snprintf` have been deleted. However, they are still there until the deprecated functions are removed from the code (see also issue #251).

**Comment by ttusar** [comment]
This is now taken care of (commit b084a2b).
There are currently no compiler warnings in the C source code.
