### ISSUE TITLE
building helper(s) code doesn't put the instance ID in the problem_id 

### ISSUE THREAD

**Issue by nikohansen** [numbbo/numbbo#199]
e.g. in the example code of `b2bob2009_attractive_sector_problem ` in `suite_building_helpers.c`

for this another helper function should be implemented like

```construct_problem_id(name, number_of_variables, instance_id)```

possibly `function_id` as input?

**Comment by ttusar** [comment]
Closed by commit a3bc14288a5adfa5dbd3b4ea76a01ce5f9a3c41 to the development branch.
