### ISSUE TITLE
Comparative Scaling Graphs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/numbbo#22]
```
Do we have comparative scaling graphs (like Fig.1)? Would they have some 
advantage over the scatter plots? 
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 13 Jun 2014 at 4:43

**Comment by brockho** [comment]
Is it clear that this issue is still valid?

**Comment by nikohansen** [comment]
We do have scaling graphs that show `ERT/dimension` vs `dimension` for several algorithms, with the advantage to the scatter plots that more than two algorithms can be displayed, but only for one `target`.

**Comment by brockho** [comment]
Given the last reply of Niko, I assume that this issue can be closed.
