### ISSUE TITLE
move GECCO-BBOB problem implementations in separate functions

### ISSUE THREAD

**Issue by nikohansen** [numbbo/numbbo#222]
As a result we should have the functions
```
problem_t *coco_problem_allocate_bbob_f1(dimension, instance)
```
etc. available to then create, for example, a single-objective GECCO-BBOB 2017 testbed. See
https://github.com/numbbo/numbbo/blob/master/code-experiments/src/suite_building_helpers.c for an attempt to simplify this process. 

This is a path to also address issue #92 in the end.

**Comment by ttusar** [comment]
Closed by commit a3bc14288a5adfa5dbd3b4ea76a01ce5f9a3c41 to the development branch.
