### ISSUE TITLE
coco_problem_duplicate is not "up-to-date"

### ISSUE THREAD

**Issue by nikohansen** [numbbo/numbbo#226]
The function `coco_problem_duplicate` in https://github.com/numbbo/numbbo/blob/master/code-experiments/src/coco_problem.c apparently does not assign all (new) internal fields. 

This also raises the question how to make sure that further changes don't introduce bugs again in this and other already existing functions?

**Comment by ttusar** [comment]
This is now taken care of (commit 85e06bd).
