### ISSUE TITLE
Need for a new mailing list?

### ISSUE THREAD

**Issue by brockho** [numbbo/numbbo#228]
After the move to github, the question remains whether we should continue to rely on the old mailing lists for people to contact us and for us to update everybody about news, releases, etc.

We should also mention this list again prominently in the new documentation and in the README.md file in particular.

**Comment by nikohansen** [comment]
FTR, currently there is quite a lot of spam in to these lists and I don't find them overly practical to handle.

**Comment by anneauger** [comment]
So now people can register easily via the google form:
https://docs.google.com/forms/d/1GS48SXGjapUu6WY6Zt-Ma5HCl2izq4ydT7sMa5ujUDI/viewform

Either we then use again the bbob-announcement mailing list ; or we make an alias with the emails we collect ; or we each time copy the list of address from the google sheet (which is quite straightforward to do ... probably quite error prone though). 

What are your thoughts?

**Comment by brockho** [comment]
now clear how to proceed with Anne's last comment, hence issue closed
