### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by brockho** [numbbo/numbbo#238]
...to take into account the latest changes in the code and the now supported operating systems, compilers, and languages

**Comment by brockho** [comment]
solved for the moment with the latest pull request (293)

**Comment by ttusar** [comment]
Is there a particular reason for linking to a closed issue here:

- coco.h is the public interface, in particular as used in the demo.c file, however check out https://code.google.com/p/numbbo/issues/detail?id=98

**Comment by nikohansen** [comment]
Depending on where this link was done, which is not clear to me from what I can see.
