### ISSUE TITLE
Naming convention for suites and observers

### ISSUE THREAD

**Issue by nikohansen** [numbbo/numbbo#257]
I would like to advocate to remove "suite_" from the name which is passed to the suite constructor and "observer_" from the name which is passed to the observer constructor. I don't see the advantage to have such prefixes (but a few disadvantages). These names are only used locally with the respective types. This would prevent to have IDs like `suite_bbob_f001_i03_d02__suite_bbob_f001_i05_d02` and it would make second guessing a name of a suite/observer simpler (I would be guess "bbob2009" or "bbob" or "BBOB" for a suite name, but never "suite_bbob").

**Comment by ttusar** [comment]
As agreed, the suites will be called 'bbob', 'bbob-noisy', and 'bbob-biobj'.

**Comment by ttusar** [comment]
We now have three suites: 'bbob', 'bbob-biobj' and 'toy' (the noisy one is not yet implemented).
Issue solved by commit e9a121c
