### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by nikohansen** [numbbo/numbbo#259]
```fatal: write error: No space left on device```
seems to be the culprit, or 
`ERROR: Error fetching remote repo 'origin'` (`Coco-experiments-test1/2-linux`)
which might have the same reason.

**Comment by ttusar** [comment]
From Dejan: Temporarily fixed, now the slave is working. I will prepare a long term solution.

**Comment by nikohansen** [comment]
Excellent, merci!

**Comment by nikohansen** [comment]
Still doesn't work for me. When I push a version to github, the build queue at `ci.inria` appears for about a second and then disappears.

**Comment by nikohansen** [comment]
By now it seems at least in parts working again.

**Comment by brockho** [comment]
can be closed after Dejan asked stuff to add more space to the master computer (for which we do not have direct access ourselves)
