### ISSUE TITLE
Make the example experiment uniform across different languages

### ISSUE THREAD

**Issue by ttusar** [numbbo/numbbo#286]
When the example experiment is run in any of the supported languages it should return the same result. 

We could have two (or more) examples per language, of which the first one should be very simple and easy to understand (without batches etc. - BTW do we still need batches now that problem filtering can be done through parameters?).

**Comment by nikohansen** [comment]
We would never need batch implementation in the running experiment code if we could be sure that any new testbed provides problem filtering as desired or necessary.

**Comment by nikohansen** [comment]
The same output would mean we also use exactly the same solver?

**Comment by ttusar** [comment]
Problem filtering is independent of the chosen suite. 

I guess 'same output' was not phrased well - I meant that all example experiments should run random search on the same benchmark (same budget, instances, dimensions etc.). Currently, this is not the case.

**Comment by nikohansen** [comment]
OK, so we need to decide for a benchmark + instance. The budget should be low, like 100 evaluations, to make it run through quickly. Given that the upcoming workshop is biobjective...

**Comment by brockho** [comment]
Current C and Java example experiments with RANDOMSARCH on 2 instances of bbob and on 10 instances of bbob-biobj for 10*dimension many function evaluations takes less than 20 seconds on my laptop. That should be okay. Leaving less than the prescribed 10 instances in the bbob-biobj example seems to have the risk to result in many incomplete submissions (rather ask the user to increase the budget than to add missing instances as we did with the old Coco code).

**Comment by nikohansen** [comment]
I suggest to _only_ change the budget compared to the final workshop setup. Otherwise it is pretty predictable that many, many submission will deviate from the desired setup.

**Comment by nikohansen** [comment]
@brockho, do we have an example where the budget is set as a function of dimension? 

It seems indeed desirable that the example code would do this.

**Comment by brockho** [comment]
All but the python example experiment implement already a maximum number of function evaluations of BUDGET*dimension, with BUDGET currently set to 10.

**Comment by nikohansen** [comment]
Python example is now revised accordingly. It runs in 4 seconds on my laptop. I tend to find the budget a little too large, because with a real algorithm it might take more time and be run many times for debugging in the beginning.

**Comment by nikohansen** [comment]
Still open: is 40-D opt-in or opt-out, depending on this we might want to change the budget.

**Comment by brockho** [comment]
Some data to support our decision (I personally can live with both opt-in and opt-out): the SMS-EMOA, run for 1e3*DIM funevals on five instances takes about 2.5 hours on my old 2009 laptop and produces 187MB of data. Of this, the entire archive eats up 186MB (!) of which 76MB (40%) are used up by the 40-D data.

**Comment by nikohansen** [comment]
moved to #346
