### ISSUE TITLE
minimal installation requirements

### ISSUE THREAD

**Issue by nikohansen** [numbbo/numbbo#311]
The minimal requirements in the readme.md mention `git`, but I don't understand why that would be necessary? 

BTW: "\`" can be used in markdown to denote code etc.

**Comment by brockho** [comment]
The reason that I mention git in the minimal requirements is that without git, the current do.py will not run, I guess. I did not test this, though, as I have no clean machine without git available at the moment. 

The backtick "trick" to typeset code in Markdown has been already used now in the Typical Workflow section of our README.md.

**Comment by nikohansen** [comment]
resolved, `do.py` should now run without `git` installed.
