### ISSUE TITLE
`bestbiobjalgentries2016.pickle` file

### ISSUE THREAD

**Issue by nikohansen** [numbbo/numbbo#347]
should be (g-)zipped as the others are. There is a large improvement in load performance in favor of zipped files. 

I added the gzipped file to the repro. Now the `.pickle.gz` file should be used and the `.pickle` file is to be removed. 

Generally, we try to abandon `pickle` files, in particular those who contain class instance objects, because this prevents to make any changes to the class without breaking the code (maybe there is a solution for this if we change the module name and import the pickle "under the old" module).

**Comment by dtusar** [comment]
Changed. Now the pickle.gz is used and the unzipped file is removed.
