### ISSUE TITLE
Different paths for postprocessing ouput

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/numbbo#42]
```
rungeneric and rungeneric1 write into different paths. This seems a little bug 
prone. 
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 16 Jun 2014 at 12:10

**Comment by brockho** [comment]
This issue can be considered closed since October 2 with the commit of Dejan (275a1208554788a4aec10feef22e131a84ff3cf0). Testing today did not show the problem anymore.
