### ISSUE TITLE
Loading pickle files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/numbbo#49]
```
benchmark the time for cPickle.load(gzip.open('testfile.pickle.gz','rb')) 
versus cPickle.load('testfile.pickle','rb') and report back (gzip might be even 
faster, because it needs to read less from disk). We like to be able to load 
.pickle and .pickle.gz files alike (e.g. in class DataSetList). 
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 16 Jun 2014 at 12:34

**Comment by brockho** [comment]
is expected to be deprecated as we do not want to use pickle files anymore (otherwise, DataSet class cannot be refactured)

**Comment by brockho** [comment]
Can be closed because we decided to not support .pickle files anymore.
