### ISSUE TITLE
doctest in __main__

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/numbbo#52]
```
doctest in __main__: find all modules and apply doctest on them 
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 16 Jun 2014 at 12:41

**Comment by brockho** [comment]
After Dejan implemented the above, it is only down to cleaning the data files for MCS, BFGS, and SMAC which I will take care of.

**Comment by brockho** [comment]
This issue can be closed now as the postprocessing tests (unit and integration tests) run through now.
