### ISSUE TITLE
provisions to generate (always) valid data

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/numbbo#88]
```
There should be some provisions that the generated data sets are valid in 
practice. 

One simple idea is to always write in a fresh folder. If the desired output 
folder already exists, the existing folder is renamed, e.g. with the current 
time stamp added. In this case, either the last or both/all folders can be used 
with the post-processing as is. 

```

Original issue reported on code.google.com by `nikolaus...@gmail.com` on 25 Feb 2015 at 3:59

**Comment by brockho** [comment]
Done for the current biobjective observer, written by Tea; should be also implemented for the BBOB observer.

**Comment by oaelhara** [comment]
Automatically done for the bbob observer from the moment it started using the same observer "object" as the biobjective one (the folder is generated using coco_create_unique_path() )

**Comment by brockho** [comment]
I suggest to close this issue then.
